<?php

namespace App\Support;

class CmsDefaults
{
    public static function settings(): array
    {
        return [
            'site_name' => 'Brevity Anderson',
            'logo_path' => asset('BREVITY_logo.png'),
            'favicon_path' => asset('favicon.ico'),
            'email' => 'info@brevityanderson.com',
            'phone' => '+44 203 890 8574',
            'address' => "15 Stratton Street, Mayfair\nLondon, W1J 8LQ, UK",
            'footer_text' => 'A world-class trade advisory firm dedicated to empowering global businesses to navigate international markets with confidence and clarity.',
            'social_links' => [
                'facebook' => '#',
                'instagram' => '#',
                'linkedin' => '#',
                'twitter' => '#',
            ],
        ];
    }

    public static function pages(): array
    {
        return [
            'home' => [
                'name' => 'Homepage',
                'key' => 'home',
                'slug' => '/',
                'template' => 'site.index',
                'title' => 'Brevity Anderson | Trade Advisory & Event Production',
                'meta_title' => 'Brevity Anderson | Trade Advisory & Event Production',
                'meta_description' => 'Brevity Anderson - World-class trade advisory firm empowering global businesses to navigate international markets with confidence and clarity.',
                'hero_badge' => 'World-Class Trade Advisory',
                'hero_title' => 'Empowering Global <span>Businesses</span> Across Markets',
                'hero_description' => 'Brevity Anderson is a premier trade advisory firm dedicated to helping businesses and governments navigate the complexities of global markets with confidence, clarity, and strategic excellence.',
                'hero_media_path' => 'video/herovid.mp4',
                'hero_media_type' => 'video',
                'primary_button_text' => 'Explore Our Services',
                'primary_button_link' => '/services',
                'secondary_button_text' => 'Get in Touch',
                'secondary_button_link' => '/contact',
                'content' => [
                    'hero_stats' => [
                        ['value' => '15', 'label' => 'Years Experience'],
                        ['value' => '500', 'label' => 'Projects Completed'],
                        ['value' => '50', 'label' => 'Global Partners'],
                        ['value' => '5', 'label' => 'Continents Covered'],
                    ],
                    'hero_slides' => [
                        [
                            'badge' => 'World-Class Trade Advisory',
                            'title' => 'Empowering Global <span>Businesses</span> Across Markets',
                            'description' => 'Brevity Anderson is a premier trade advisory firm dedicated to helping businesses and governments navigate the complexities of global markets with confidence, clarity, and strategic excellence.',
                        ],
                        [
                            'badge' => 'Strategic Investment Promotion',
                            'title' => 'Connecting Nations with <span>High-Value</span> Opportunities',
                            'description' => 'We partner with governments, investors, and institutions to design market-entry strategies, unlock capital flows, and accelerate sustainable cross-border growth.',
                        ],
                        [
                            'badge' => 'Energy And Events Expertise',
                            'title' => 'Delivering Impact Across <span>Oil, Gas</span> and Global Forums',
                            'description' => 'From sector-specific trade missions to world-class event production, our team creates platforms that strengthen partnerships, de-risk expansion, and drive measurable outcomes.',
                        ],
                    ],
                ],
                'is_published' => true,
            ],
            'about' => [
                'name' => 'About Us',
                'key' => 'about',
                'slug' => 'about-us',
                'template' => 'site.about-us',
                'title' => 'About Us | Brevity Anderson',
                'meta_title' => 'About Us | Brevity Anderson',
                'meta_description' => 'Learn about Brevity Anderson - Our vision, mission, and commitment to excellence in international trade advisory and event production.',
                'hero_badge' => 'About Brevity Anderson',
                'hero_title' => 'Driven by strategy, relationships, and measurable impact.',
                'hero_description' => 'We bring together expertise in trade advisory, stakeholder engagement, and premium event delivery to help organizations thrive.',
                'primary_button_text' => 'Contact Us',
                'primary_button_link' => '/contact',
                'secondary_button_text' => 'View Services',
                'secondary_button_link' => '/services',
                'content' => [],
                'is_published' => true,
            ],
            'services' => [
                'name' => 'Services',
                'key' => 'services',
                'slug' => 'services',
                'template' => 'site.services',
                'title' => 'Services | Brevity Anderson',
                'meta_title' => 'Services | Brevity Anderson',
                'meta_description' => 'Explore Brevity Anderson services in conferences, exhibitions, trade advisory, hybrid events, and strategic stakeholder engagement.',
                'hero_badge' => 'Our Services',
                'hero_title' => 'Services crafted for visibility, value, and lasting impact.',
                'hero_description' => 'We support brands and institutions with end-to-end event production and strategic advisory solutions tailored to ambitious outcomes.',
                'primary_button_text' => 'Start a Project',
                'primary_button_link' => '/contact',
                'secondary_button_text' => 'View Gallery',
                'secondary_button_link' => '/gallery',
                'content' => [],
                'is_published' => true,
            ],
            'clientele' => [
                'name' => 'Clientele',
                'key' => 'clientele',
                'slug' => 'clientele',
                'template' => 'site.clientele',
                'title' => 'Clientele | Brevity Anderson',
                'meta_title' => 'Clientele | Brevity Anderson',
                'meta_description' => 'See the institutions, governments, and global brands that trust Brevity Anderson for advisory and event delivery.',
                'hero_badge' => 'Our Clientele',
                'hero_title' => 'Trusted by governments, institutions, and global brands.',
                'hero_description' => 'Our partnerships span energy, policy, investment, and development organizations committed to high-value engagement.',
                'primary_button_text' => 'Work With Us',
                'primary_button_link' => '/contact',
                'secondary_button_text' => 'See Gallery',
                'secondary_button_link' => '/gallery',
                'content' => [],
                'is_published' => true,
            ],
            'gallery' => [
                'name' => 'Gallery',
                'key' => 'gallery',
                'slug' => 'gallery',
                'template' => 'site.gallery',
                'title' => 'Gallery | Brevity Anderson',
                'meta_title' => 'Gallery | Brevity Anderson',
                'meta_description' => 'Browse event highlights, exhibitions, conferences, and strategic meetings delivered by Brevity Anderson.',
                'hero_badge' => 'Event Highlights',
                'hero_title' => 'Moments that capture our standard of excellence.',
                'hero_description' => 'A closer look at conferences, exhibitions, and strategic gatherings we have helped bring to life.',
                'primary_button_text' => 'Contact Us',
                'primary_button_link' => '/contact',
                'secondary_button_text' => 'View Services',
                'secondary_button_link' => '/services',
                'content' => [],
                'is_published' => true,
            ],
            'contact' => [
                'name' => 'Contact',
                'key' => 'contact',
                'slug' => 'contact',
                'template' => 'site.contact',
                'title' => 'Contact | Brevity Anderson',
                'meta_title' => 'Contact | Brevity Anderson',
                'meta_description' => 'Reach out to Brevity Anderson for trade advisory, event production, and strategic meeting support.',
                'hero_badge' => 'Get In Touch',
                'hero_title' => 'Let us build your next high-impact engagement.',
                'hero_description' => 'Talk to our team about conferences, exhibitions, advisory support, and strategic stakeholder events.',
                'primary_button_text' => 'Email Us',
                'primary_button_link' => 'mailto:info@brevityanderson.com',
                'secondary_button_text' => 'Call Us',
                'secondary_button_link' => 'tel:+2348030000000',
                'content' => [],
                'is_published' => true,
            ],
        ];
    }

    public static function sections(): array
    {
        return [
            'home' => [
                'about_preview' => [
                    'name' => 'About Preview',
                    'key' => 'about_preview',
                    'title' => 'About Us',
                    'subtitle' => 'Welcome to Brevity Anderson',
                    'body' => 'Brevity Anderson is a world-class trade advisory firm dedicated to empowering global businesses to navigate the complexities of global markets with confidence and clarity.',
                    'image_path' => 'img/about.jpg',
                    'button_text' => 'Learn More About Us',
                    'button_link' => '/about-us',
                    'content' => [
                        'experience_years' => '15+',
                        'experience_label' => 'Years of Excellence',
                        'paragraphs' => [
                            'Brevity Anderson is a world-class trade advisory firm dedicated to empowering global businesses to navigate the complexities of global markets with confidence and clarity. We also work with governments at the highest levels to promote trade and inward investment. Our team of seasoned experts combine deep industry knowledge, strategic insight, and hands-on experience to deliver tailored solutions that drive growth, minimise risk, and unlock new opportunities across borders. Our particular expertise in the Oil, Gas and Energy space has positioned us as a strategic partner for governments, multinational organisations and some of the leading brands globally.',
                            'From trade compliance and regulatory strategy to market entry and supply chain optimization, we provide end-to-end advisory services that position our clients for sustainable success in an increasingly interconnected economy. With a proven track record of excellence and innovation, Brevity Anderson has evolved into one of the most trusted names in this space.',
                            'Our conference and events division is at the forefront of what we do, gathering world leaders, industry experts and helping to generate the connections that get the biggest deals over the line.',
                        ],
                    ],
                    'sort_order' => 10,
                    'is_active' => true,
                ],
                'strategic_advisory' => [
                    'name' => 'Strategic Advisory',
                    'key' => 'strategic_advisory',
                    'title' => 'Strategic',
                    'subtitle' => 'Trade Advisory',
                    'body' => 'Expanding into new markets comes with both opportunities and complexities, and that is where we make the difference for private companies of every size.',
                    'button_text' => 'Talk to Us',
                    'button_link' => '/contact',
                    'content' => [
                        'cards' => [
                            ['title' => 'Private Sector Advisory', 'body' => 'Expanding into new markets comes with both opportunities and complexities, and that is where we make the difference for private companies of every size.'],
                            ['title' => 'Government Advisory', 'body' => 'Governments can trust our advisory work in promoting trade and facilitating inward investment.'],
                            ['title' => 'Event Production Expertise', 'body' => 'Our event production team is made up of some of the best hands in the industry, and we look forward to taking your event to the next level.'],
                        ],
                    ],
                    'sort_order' => 20,
                    'is_active' => true,
                ],
                'services_preview' => [
                    'name' => 'Services Preview',
                    'key' => 'services_preview',
                    'title' => 'Our Services',
                    'subtitle' => 'Event Services Crafted for Impact',
                    'body' => 'We deliver premium event experiences across physical, digital, and executive environments with the precision, polish, and strategic depth global audiences expect.',
                    'button_text' => 'View All Services',
                    'button_link' => '/services',
                    'content' => [
                        'items' => [
                            ['title' => 'Conferences & Exhibitions', 'body' => 'We create compelling conferences and exhibition platforms that bring together industry leaders, partners, and audiences in high-value live environments.', 'image_path' => 'img/CONFERENCES & EXHIBITIONS.png'],
                            ['title' => 'Virtual and Hybrid Events', 'body' => 'From digital broadcasts to hybrid experiences, we design seamless event journeys that connect in-room and remote audiences without compromise.', 'image_path' => 'img/VIRTUAL AND HYBRID EVENTS.png'],
                            ['title' => 'Strategic High-Level Meetings', 'body' => 'We coordinate executive-level meetings and high-stakes engagements with the discretion, structure, and detail they demand.', 'image_path' => 'img/STRATEGIC HIGH-LEVEL MEETINGS.png'],
                        ],
                    ],
                    'sort_order' => 30,
                    'is_active' => true,
                ],
                'clientele' => [
                    'name' => 'Clientele',
                    'key' => 'clientele',
                    'title' => 'Our Clientele',
                    'subtitle' => 'Trusted by Governments and Global Brands',
                    'body' => 'We are proud to support public institutions, multinational companies, and industry leaders with trade advisory, strategic events, and market-facing solutions.',
                    'content' => [
                        'logos' => [
                            ['image_path' => 'img/clientele/apple-logo.png', 'alt' => 'Apple logo'],
                            ['image_path' => 'img/clientele/APPO-logo_200x200.jpg', 'alt' => 'APPO logo'],
                            ['image_path' => 'img/clientele/CBWN-LOGO_200x200.png', 'alt' => 'CBWN logo'],
                            ['image_path' => 'img/clientele/chevron1_200x200.png', 'alt' => 'Chevron logo'],
                            ['image_path' => 'img/clientele/Coat-of-arms_200x200.png', 'alt' => 'Coat of arms logo'],
                            ['image_path' => 'img/clientele/cordros.png', 'alt' => 'Cordros logo'],
                            ['image_path' => 'img/clientele/Dangote_200x200.png', 'alt' => 'Dangote logo'],
                            ['image_path' => 'img/clientele/DIT2.png', 'alt' => 'DIT logo'],
                        ],
                    ],
                    'sort_order' => 40,
                    'is_active' => true,
                ],
                'why_choose' => [
                    'name' => 'Why Choose Us',
                    'key' => 'why_choose',
                    'title' => 'Why Choose Us',
                    'subtitle' => 'What Sets Us Apart',
                    'body' => 'Our clients are at the heart of everything we do. Every solution we design is driven by their goals, challenges, and aspirations.',
                    'content' => [
                        'items' => [
                            ['title' => 'Proven Excellence', 'body' => 'Over 15 years of delivering exceptional results for global clients across multiple industries and continents.'],
                            ['title' => 'Expert Team', 'body' => 'Seasoned professionals with deep industry knowledge and hands-on experience in international trade.'],
                            ['title' => 'Innovative Solutions', 'body' => 'Tailored strategies that address unique challenges and unlock new opportunities in global markets.'],
                            ['title' => 'Lasting Partnerships', 'body' => 'Building relationships founded on trust, collaboration, and measurable impact for our clients.'],
                        ],
                    ],
                    'sort_order' => 50,
                    'is_active' => true,
                ],
                'testimonials' => [
                    'name' => 'Testimonials',
                    'key' => 'testimonials',
                    'title' => 'Testimonials',
                    'subtitle' => 'What our clients say',
                    'body' => 'The trust we earn is reflected in the relationships we maintain and the outcomes we deliver.',
                    'content' => [
                        'items' => [
                            ['quote' => 'An exceptional team with strong strategic thinking and flawless execution.', 'author' => 'Client Stakeholder'],
                            ['quote' => 'Their ability to manage high-level events with calm precision stands out.', 'author' => 'Program Partner'],
                        ],
                    ],
                    'sort_order' => 55,
                    'is_active' => true,
                ],
                'contact_cta' => [
                    'name' => 'Contact CTA',
                    'key' => 'contact_cta',
                    'title' => 'Ready to Expand Your Global Reach?',
                    'subtitle' => 'Strategic objectives start with the right conversation.',
                    'body' => "Let's discuss how Brevity Anderson can help you achieve your strategic objectives in international markets.",
                    'button_text' => 'Start a Conversation',
                    'button_link' => '/contact',
                    'sort_order' => 60,
                    'is_active' => true,
                ],
                'footer' => [
                    'name' => 'Footer',
                    'key' => 'footer',
                    'title' => 'Brevity Anderson',
                    'subtitle' => 'Trade Advisory',
                    'body' => 'A world-class trade advisory firm dedicated to empowering global businesses to navigate international markets with confidence and clarity.',
                    'content' => [
                        'quick_links' => [
                            ['label' => 'Home', 'link' => '/'],
                            ['label' => 'About Us', 'link' => '/about-us'],
                            ['label' => 'Services', 'link' => '/services'],
                            ['label' => 'Clientele', 'link' => '/clientele'],
                            ['label' => 'Contact', 'link' => '/contact'],
                        ],
                        'service_links' => [
                            ['label' => 'Conferences & Exhibitions', 'link' => '/services'],
                            ['label' => 'Virtual and Hybrid Events', 'link' => '/services'],
                            ['label' => 'Strategic High-Level Meetings', 'link' => '/services'],
                        ],
                    ],
                    'sort_order' => 70,
                    'is_active' => true,
                ],
            ],
        ];
    }
}
